import Navbar from '@/components/ui/Navbar';
import { ThemeProvider } from '@/components/ui/ThemeProvider';
import { config } from '@/config';
import Web3ModalProvider from '@/context';
import { AppProvider } from '@/context/AppContext';
import SnackbarProvider from '@/context/SnackbarContext';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import './globals.css';

const kanit = Kanit({
    weight: '300',
    style: 'normal',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'));
    return (
        <html lang='en'>
            <body className={kanit.className}>
                <ThemeProvider>
                    <SnackbarProvider>
                        <Web3ModalProvider initialState={initialState}>
                            <AppProvider>
                                <Navbar />
                                {children}
                            </AppProvider>
                        </Web3ModalProvider>
                    </SnackbarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
