import Navbar from '@/components/ui/Navbar';
import { ThemeProvider } from '@/components/ui/ThemeProvider';
import { config } from '@/config';
import Web3ModalProvider from '@/context';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'));
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ThemeProvider>
                    <Web3ModalProvider initialState={initialState}>
                        <Navbar />
                        {children}
                    </Web3ModalProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
